version: '3'

services:
  apache:
    build: bin/apache
    ports:
      - 2121:80
    volumes:
      - ./html/:/var/www/html
      - ./apache/sites-enabled:/etc/apache2/sites-enabled
      - ./logs:/var/log/apache2
    environment:
       APACHE_LOG_DIR: /var/log/apache2
    restart: always
